// <auto-generated />
using System;
using Flights.Details;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flights.Migrations
{
    [DbContext(typeof(Flightdetailsdbcontext))]
    [Migration("20230603053357_Initial Migrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flights.Models.Domain.FlightData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("arrival_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("arrival_destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("departure_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("departure_destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flightid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FlightDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
